name: CI

on:
  push:
    branches:
    - feature/**
    - feat/**
    - fix/**
    - chore/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven
      - run: mvn clean install